### ISSUE TITLE
Using not allowed functions

### ISSUE THREAD

**Issue by Nikola-Prljic** [zstenger93/python_piscine#1]
Starting 0 -  ex08  - Loading.py
You are importing 2 libraries, the subject says "Allowed functions: None"

**Comment by zstenger93** [comment]
If you look at the project I finished about 8 months ago, it could have been different (not like I remember). Also, you don't have to use the second import, I did it for a good reason which you will understand if you spend more time on the task. Regarding the time, somehow you need to get it :)
